# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# do not build anything just because we commit to the pipeline
trigger:
  branches:
    exclude:
    - '*'

# instead, perform scheduled builds only (besides manually queued ones)
schedules:
  - cron: "0 12 * * 1"
    displayName: Weekly build
    branches:
      include:
      - master
    always: true

stages:

# - template: docker/seven-stages.yml
#   parameters:
#       image: windows-2019
#       variant: "guest_64bit_cygwin2019"

#  - stage: "MacOS"
#    dependsOn: []
#    jobs:
#      - job: "Prefix"
#        timeoutInMinutes: 0
#        strategy:
#          matrix:
#            current:
#              macOS_version: 'macOS'
#            highSierra:
#              macOS_version: 'macOS High Sierra'
#        pool:
#          name: 'Hosted $(macOS_version)'
#        steps:
#        - script: set
#          displayName: 'MacOS Info'
#        - script: ./macos/prefix.sh
#          timeoutInMinutes: 0
#          displayName: 'MacOS Prefix'

  - template: docker/two-stages.yml
    parameters:
        variant: "rap_64bit_fedora"
  - template: docker/two-stages.yml
    parameters:
        variant: "guest_64bit_fedora"
  - template: docker/two-stages.yml
    parameters:
        variant: "rap_32bit_fedora"
  - template: docker/two-stages.yml
    parameters:
        variant: "guest_32bit_fedora"

  - template: docker/two-stages.yml
    parameters:
        variant: "rap_64bit_fedora28"
  - template: docker/two-stages.yml
    parameters:
        variant: "guest_64bit_fedora28"
  - template: docker/two-stages.yml
    parameters:
        variant: "rap_32bit_fedora28"
  - template: docker/two-stages.yml
    parameters:
        variant: "guest_32bit_fedora28"

  - template: docker/two-stages.yml
    parameters:
        variant: "rap_64bit_opensuse15"
  - template: docker/two-stages.yml
    parameters:
        variant: "guest_64bit_opensuse15"
  - template: docker/two-stages.yml
    parameters:
        variant: "rap_32bit_opensuse15"
  - template: docker/two-stages.yml
    parameters:
        variant: "guest_32bit_opensuse15"

  - template: docker/two-stages.yml
    parameters:
        variant: "rap_64bit_opensuse16"
  - template: docker/two-stages.yml
    parameters:
        variant: "guest_64bit_opensuse16"
  - template: docker/two-stages.yml
    parameters:
        variant: "rap_32bit_opensuse16"
  - template: docker/two-stages.yml
    parameters:
        variant: "guest_32bit_opensuse16"

  - template: docker/two-stages.yml
    parameters:
        variant: "rap_64bit_ubuntu"
  - template: docker/two-stages.yml
    parameters:
        variant: "rap_32bit_ubuntu"

  - template: docker/two-stages.yml
    parameters:
        variant: "rap_64bit_ubuntu16"
  - template: docker/two-stages.yml
    parameters:
        variant: "rap_32bit_ubuntu16"

  - template: docker/two-stages.yml
    parameters:
        variant: "rap_64bit_centos8"
  - template: docker/two-stages.yml
    parameters:
        variant: "guest_64bit_centos8"
  - template: docker/two-stages.yml
    parameters:
        variant: "rap_32bit_centos8"
  - template: docker/two-stages.yml
    parameters:
        variant: "guest_32bit_centos8"

  - template: docker/two-stages.yml
    parameters:
        variant: "rap_64bit_centos7"
  - template: docker/two-stages.yml
    parameters:
        variant: "guest_64bit_centos7"
  - template: docker/two-stages.yml
    parameters:
        variant: "rap_32bit_centos7"
  - template: docker/two-stages.yml
    parameters:
        variant: "guest_32bit_centos7"

  - template: docker/two-stages.yml
    parameters:
        variant: "rap_64bit_centos6"
  - template: docker/two-stages.yml
    parameters:
        variant: "guest_64bit_centos6"
  - template: docker/two-stages.yml
    parameters:
        variant: "rap_32bit_centos6"
  - template: docker/two-stages.yml
    parameters:
        variant: "guest_32bit_centos6"
