
# Create user
# Give the user a password
RUN set -x \
  ; cat /etc/*-release \
  ; set -e \
  ; date -u -R \
  ; cat /etc/group \
  ; useradd --user-group --create-home --shell=/bin/bash user \
  ; ls -la /home/user \
  ; cat /etc/group \
  ; echo user:user | chpasswd \
  ; date -u -R

WORKDIR /home/user
USER user
